mlflow:
    endpoint_url: http://minio.minio.svc.cluster.local:9000
    access_key_id: minio
    secret_access_key: minio123
    tracking_uri: http://mlflow.mlflow.svc.cluster.local:5000

kubeflow:
    username: user@example.com
    password: "12341234"
    namespace: kubeflow-user-example-com
    host: http://localhost:8080
